"""empty message

Revision ID: 02a76eb24851
Revises: 4630536578ce
Create Date: 2024-11-26 16:30:20.334468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a76eb24851'
down_revision: Union[str, None] = '4630536578ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objectives',
    sa.Column('objectiveId', sa.UUID(), nullable=False),
    sa.Column('objectiveName', sa.String(), nullable=False),
    sa.Column('objectiveDescription', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('objectiveId')
    )
    op.create_table('projects',
    sa.Column('projectId', sa.UUID(), nullable=False),
    sa.Column('projectName', sa.String(), nullable=False),
    sa.Column('projectDescription', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('projectId')
    )
    op.create_table('teams',
    sa.Column('teamId', sa.UUID(), nullable=False),
    sa.Column('teamMame', sa.String(), nullable=True),
    sa.Column('teamDescription', sa.String(), nullable=True),
    sa.Column('createdAt', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('teamId')
    )
    op.create_table('projects_objectives',
    sa.Column('projectObjectiveId', sa.UUID(), nullable=False),
    sa.Column('projectId', sa.UUID(), nullable=False),
    sa.Column('objectiveId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['objectiveId'], ['objectives.objectiveId'], ),
    sa.ForeignKeyConstraint(['projectId'], ['projects.projectId'], ),
    sa.PrimaryKeyConstraint('projectObjectiveId')
    )
    op.create_table('team_members',
    sa.Column('teamMemberId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('teamId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['teams.teamId'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('teamMemberId')
    )
    op.create_table('teams_projects',
    sa.Column('teamProjectId', sa.UUID(), nullable=False),
    sa.Column('teamId', sa.UUID(), nullable=False),
    sa.Column('projectId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.projectId'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.teamId'], ),
    sa.PrimaryKeyConstraint('teamProjectId')
    )
    op.create_table('underobjectives',
    sa.Column('underobjectiveId', sa.UUID(), nullable=False),
    sa.Column('underobjectiveName', sa.String(), nullable=False),
    sa.Column('underobjectiveDescription', sa.String(), nullable=True),
    sa.Column('objectiveId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['objectiveId'], ['objectives.objectiveId'], ),
    sa.PrimaryKeyConstraint('underobjectiveId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('underobjectives')
    op.drop_table('teams_projects')
    op.drop_table('team_members')
    op.drop_table('projects_objectives')
    op.drop_table('teams')
    op.drop_table('projects')
    op.drop_table('objectives')
    # ### end Alembic commands ###
