"""empty message

Revision ID: 8e123518ebf0
Revises: 02a76eb24851
Create Date: 2024-11-27 16:59:23.431368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e123518ebf0'
down_revision: Union[str, None] = '02a76eb24851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('teamName', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('leaderId', sa.UUID(), nullable=False))
    op.drop_column('teams', 'teamMame')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('teamMame', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('teams', 'leaderId')
    op.drop_column('teams', 'teamName')
    # ### end Alembic commands ###
