"""init

Revision ID: 947fe4fd803f
Revises: 
Create Date: 2024-11-22 15:55:44.327803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947fe4fd803f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_objectives',
    sa.Column('generalObjectiveId', sa.UUID(), nullable=False),
    sa.Column('generalObjectiveName', sa.String(length=50), nullable=False),
    sa.Column('generalObjectiveDescription', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('generalObjectiveId'),
    sa.UniqueConstraint('generalObjectiveName')
    )
    op.create_table('projects',
    sa.Column('projectId', sa.UUID(), nullable=False),
    sa.Column('projectTitle', sa.String(length=50), nullable=False),
    sa.Column('projectDescription', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('projectId'),
    sa.UniqueConstraint('projectTitle')
    )
    op.create_table('users',
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('registered', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('login')
    )
    op.create_table('profiles',
    sa.Column('userProfileId', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('userProfileId')
    )
    op.create_table('project_objectives',
    sa.Column('projectTaskId', sa.UUID(), nullable=False),
    sa.Column('generalObjectiveId', sa.UUID(), nullable=False),
    sa.Column('projectId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['generalObjectiveId'], ['general_objectives.generalObjectiveId'], ),
    sa.ForeignKeyConstraint(['projectId'], ['projects.projectId'], ),
    sa.PrimaryKeyConstraint('projectTaskId')
    )
    op.create_table('team_projects',
    sa.Column('teamProjectid', sa.UUID(), nullable=False),
    sa.Column('projectId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.projectId'], ),
    sa.PrimaryKeyConstraint('teamProjectid')
    )
    op.create_table('teams',
    sa.Column('teamId', sa.UUID(), nullable=False),
    sa.Column('teamName', sa.String(length=50), nullable=False),
    sa.Column('teamDescription', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.Date(), nullable=False),
    sa.Column('creatorId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['creatorId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('teamId'),
    sa.UniqueConstraint('teamName')
    )
    op.create_table('under_objectives',
    sa.Column('underObjectiveId', sa.UUID(), nullable=False),
    sa.Column('underObjectiveName', sa.String(length=50), nullable=False),
    sa.Column('underObjectiveDescription', sa.String(length=255), nullable=False),
    sa.Column('generalObjectiveId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['generalObjectiveId'], ['general_objectives.generalObjectiveId'], ),
    sa.PrimaryKeyConstraint('underObjectiveId'),
    sa.UniqueConstraint('underObjectiveName')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('under_objectives')
    op.drop_table('teams')
    op.drop_table('team_projects')
    op.drop_table('project_objectives')
    op.drop_table('profiles')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('general_objectives')
    # ### end Alembic commands ###
