"""empty message

Revision ID: e295c86a8c25
Revises: 0142566cf9f6
Create Date: 2024-11-24 10:58:11.864293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e295c86a8c25'
down_revision: Union[str, None] = '0142566cf9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'registered',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'registered',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
