"""empty message

Revision ID: 1f12e259bc37
Revises: 9de830d79c1b
Create Date: 2024-11-26 15:40:55.512177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f12e259bc37'
down_revision: Union[str, None] = '9de830d79c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('birthdate', sa.Date(), nullable=True))
    op.alter_column('user_profiles', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_profiles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_profiles', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_profiles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_profiles', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user_profiles', 'birthdate')
    # ### end Alembic commands ###
