"""empty message

Revision ID: 22597e49a182
Revises: 
Create Date: 2024-12-13 14:30:04.470846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22597e49a182'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_invitations',
    sa.Column('teamInvitationId', sa.UUID(), nullable=False),
    sa.Column('invited_user_id', sa.UUID(), nullable=False),
    sa.Column('invited_by_leader_id', sa.UUID(), nullable=False),
    sa.Column('teamId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_leader_id'], ['users.userId'], ),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.userId'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.teamId'], ),
    sa.PrimaryKeyConstraint('teamInvitationId')
    )
    op.add_column('teams', sa.Column('leaderId', sa.UUID(), nullable=True))
    op.drop_constraint('teams_organizationId_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'organizations', ['organizationId'], ['organizationId'], ondelete='SET NULL')
    op.create_foreign_key(None, 'teams', 'users', ['leaderId'], ['userId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('teams_organizationId_fkey', 'teams', 'organizations', ['organizationId'], ['organizationId'])
    op.drop_column('teams', 'leaderId')
    op.drop_table('team_invitations')
    # ### end Alembic commands ###
