"""empty message

Revision ID: 6cd626781d1d
Revises: 22597e49a182
Create Date: 2024-12-13 17:39:53.680220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd626781d1d'
down_revision: Union[str, None] = '22597e49a182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('leaderId', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'organizations', 'users', ['leaderId'], ['userId'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'leaderId')
    # ### end Alembic commands ###
