"""empty message

Revision ID: b905fe5accfc
Revises: 413a0a1e2a82
Create Date: 2024-12-10 16:44:54.622936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b905fe5accfc'
down_revision: Union[str, None] = '413a0a1e2a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('leaderId', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['leaderId'], ['userId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'leaderId')
    # ### end Alembic commands ###
