run:
	docker-compose --env-file .env -f docker/docker-compose.yml --project-directory . up --build

dev:
	docker-compose --env-file .env.develop -f docker/docker-compose.yml --project-directory . up --build

	

