"""empty message

Revision ID: 19aea4047442
Revises: 
Create Date: 2024-11-17 23:01:04.221558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19aea4047442'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_objectives',
    sa.Column('generalObjectiveId', sa.Integer(), nullable=False),
    sa.Column('generalObjectiveName', sa.String(length=50), nullable=False),
    sa.Column('generalObjectiveDescription', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('generalObjectiveId'),
    sa.UniqueConstraint('generalObjectiveName')
    )
    op.create_table('users',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('registered', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('login')
    )
    op.create_table('profiles',
    sa.Column('userProfileId', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('userProfileId')
    )
    op.create_table('team_objectives',
    sa.Column('teamObjectiveId', sa.Integer(), nullable=False),
    sa.Column('generalObjectiveId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generalObjectiveId'], ['general_objectives.generalObjectiveId'], ),
    sa.PrimaryKeyConstraint('teamObjectiveId')
    )
    op.create_table('teams',
    sa.Column('teamId', sa.Integer(), nullable=False),
    sa.Column('teamName', sa.String(length=50), nullable=False),
    sa.Column('teamDescription', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.Date(), nullable=False),
    sa.Column('creatorId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creatorId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('teamId'),
    sa.UniqueConstraint('teamName')
    )
    op.create_table('under_objectives',
    sa.Column('underObjectiveId', sa.Integer(), nullable=False),
    sa.Column('underObjectiveName', sa.String(length=50), nullable=False),
    sa.Column('underObjectiveDescription', sa.String(length=255), nullable=False),
    sa.Column('generalObjectiveId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generalObjectiveId'], ['general_objectives.generalObjectiveId'], ),
    sa.PrimaryKeyConstraint('underObjectiveId'),
    sa.UniqueConstraint('underObjectiveName')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('under_objectives')
    op.drop_table('teams')
    op.drop_table('team_objectives')
    op.drop_table('profiles')
    op.drop_table('users')
    op.drop_table('general_objectives')
    # ### end Alembic commands ###
